// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slaughter_House.Models;

#nullable disable

namespace Slaughter_House.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20230626100505_AddProfileRelationship")]
    partial class AddProfileRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Slaughter_House.Models.AddProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Camel")
                        .HasColumnType("bit");

                    b.Property<bool>("Day1Slot1")
                        .HasColumnType("bit");

                    b.Property<bool>("Day1Slot2")
                        .HasColumnType("bit");

                    b.Property<bool>("Day1Slot3")
                        .HasColumnType("bit");

                    b.Property<bool>("Day2Slot1")
                        .HasColumnType("bit");

                    b.Property<bool>("Day2Slot2")
                        .HasColumnType("bit");

                    b.Property<bool>("Day2Slot3")
                        .HasColumnType("bit");

                    b.Property<bool>("Day3Slot1")
                        .HasColumnType("bit");

                    b.Property<bool>("Day3Slot2")
                        .HasColumnType("bit");

                    b.Property<bool>("Day3Slot3")
                        .HasColumnType("bit");

                    b.Property<bool>("Goat")
                        .HasColumnType("bit");

                    b.Property<bool>("Sheep")
                        .HasColumnType("bit");

                    b.HasKey("Username");

                    b.ToTable("AddProfiles");
                });

            modelBuilder.Entity("Slaughter_House.Models.RegisteredButcher", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Liability")
                        .HasColumnType("bit");

                    b.Property<string>("Medical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Slaughter_House.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Slaughter_House.Models.AddProfile", b =>
                {
                    b.HasOne("Slaughter_House.Models.RegisteredButcher", "RegisteredButcher")
                        .WithOne("AddProfile")
                        .HasForeignKey("Slaughter_House.Models.AddProfile", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredButcher");
                });

            modelBuilder.Entity("Slaughter_House.Models.RegisteredButcher", b =>
                {
                    b.Navigation("AddProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
